let a = 5;
let b = 2;
let c = 0;
console.log(a + b);
console.log(a - b);
console.log(a + c);
try {
    console.log(a / d);

} catch (err) {
    console.log(err)
}
// if any error would occur then the code would stop at that point of error now with try and catch woulnt stop
console.log(a - c);
